name: SonarCloud Quality Code Analysis for Node.js with Yarn
on:
  workflow_call:
    inputs:
      sonar-project-key:
        required: false
        type: string
        description: "SonarCloud project key (required if sonar-project.properties does not exist)"
        default: ""
      sonar-organization:
        required: false
        type: string
        description: "SonarCloud organization (required if sonar-project.properties does not exist)"
        default: "n1co"
      env-name:
        required: true
        type: string
        description: "Environment name"
      node-version:
        required: false
        type: string
        description: "Node.js version"
        default: "18"
      build-path:
        required: false
        type: string
        description: "Path to build project"
        default: "."

jobs:
  sonarcloud-analysis:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env-name }}
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        working-directory: ${{ inputs.build-path }}
        run: yarn install --frozen-lockfile

      - name: Run tests with coverage
        working-directory: ${{ inputs.build-path }}
        run: yarn test:coverage

      - name: Check for sonar-project.properties file
        id: check_sonar
        run: |
          if [[ -f "./sonar-project.properties" ]]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: SonarCloud Scan with sonar-project.properties
        if: steps.check_sonar.outputs.exists == 'true'
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ inputs.build-path }}

      - name: SonarCloud Scan without sonar-project.properties
        if: steps.check_sonar.outputs.exists == 'false'
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ inputs.build-path }}
          args: >
            -Dsonar.projectKey=${{ inputs.sonar-project-key }}
            -Dsonar.organization=${{ inputs.sonar-organization }}
            -Dsonar.sources=${{ inputs.build-path }}
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
            -Dsonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts
            -Dsonar.exclusions=/node_modules/,/coverage/,/dist/,/build/,.wrangler/,/.git/,/tests/,/src/test/**
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.javascript.file.suffixes=.js,.jsx
            -Dsonar.typescript.file.suffixes=.ts,.tsx

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-and-test-results
          path: |
            ${{ inputs.build-path }}/coverage
